### ISSUE TITLE
Need syntax highlighting for << >>, <PRIVATE PRIVATE>, eval(, $[, S{, DL{, L{

### ISSUE THREAD

**Issue by h0le** [rkoeninger/sublime-factor#12]
It does not highlight `<< ... >>`, `<PRIVATE ... PRIVATE>`, `eval(`, `$[`, `S{`, `DL{`, `L{`.

**Comment by rkoeninger** [comment]
@v0idNULL Would you want to highlight the code between `<<` and `>>`  any differently or just the individual symbols as keywords? Highlighting the code between differently would be a bit more work.

**Comment by h0le** [comment]
@rkoeninger It should highlight doubled angle brackets only as individual symbols.

**Comment by rkoeninger** [comment]
@v0idNULL It looks like you're still finding symbols to add, so just open a PR when you're done looking.
