### ISSUE TITLE
Incorrect comments form

### ISSUE THREAD

**Issue by h0le** [rkoeninger/sublime-factor#13]
It is need to correct form of comments like: !␣... instead of incorrect one: !... .

**Comment by rkoeninger** [comment]
@v0idNULL Do you mean there should be a space after the comment? And you mean the `Ctrl + /` command should include the space? Or do you mean comments should be highlighted differently?

**Comment by h0le** [comment]
It should be always some space between exclamation mark and next word if it available. Otherwise, it is treated as a whole word.

**Comment by rkoeninger** [comment]
This was fixed in [release 0.1.11](https://github.com/rkoeninger/sublime-factor/releases/tag/v0.1.11). Should be up on package control in a few hours.
