### ISSUE TITLE
Bug with highlighting sequence literals after some parsing words

### ISSUE THREAD

**Issue by h0le** [rkoeninger/sublime-factor#18]
It does not highlight sequence literals after some parsing words ended with `:`, like `SYNTAX:` or `TUPLE:`.
![bug2](https://user-images.githubusercontent.com/4871017/43363983-5fd97976-9354-11e8-8ca6-edc3f44f6093.png)

**Comment by h0le** [comment]
Some more for comparison.
![bug4](https://user-images.githubusercontent.com/4871017/43364612-d1f68330-9360-11e8-8760-e8a9fc568ca0.png)
And for string literals.
![bug5](https://user-images.githubusercontent.com/4871017/43364645-ac36a502-9361-11e8-9ea0-efdff17c30dd.png)

**Comment by rkoeninger** [comment]
@v0idNULL  Not all directives can be covered by highlighting. For directives not covered by the syntax definition, the new behavior is to highlight anything after the ABC: like expressions in word definitions (excluding bracket/paren/brace groups) and terminate on either a semicolon or a newline (no guarantee an unknown directive needs to terminate on a semicolon).

`TUPLE:` has some highlighting but not for your example. Something like `TUPLE: circle < shape center radius ;` works.

It's also hard to provide custom highlighting for `SYNTAX:` as its contents are arbitrary.

This is as of the next v0.1.16 release.

Let me know if there are any other issues.
