### ISSUE TITLE
Bug with highlighting complex stack effects

### ISSUE THREAD

**Issue by h0le** [rkoeninger/sublime-factor#20]
It does not highlight all brackets in complex stack effects. For example:
![bug3](https://user-images.githubusercontent.com/4871017/43364050-dee85e48-9355-11e8-9ed0-a3ecf3c3f0f9.png)

**Comment by rkoeninger** [comment]
@v0idNULL This appears to be fixed in v0.1.15

**Comment by rkoeninger** [comment]
Let me know if this is still happening or any other issues.
