### ISSUE TITLE
Need syntax highlighting for W{

### ISSUE THREAD

**Issue by h0le** [rkoeninger/sublime-factor#4]
It does not highlight W{ .

**Comment by rkoeninger** [comment]
@v0idNULL  Do you want to make a PR for this? It's not hard to do, but it's taking up time.

Refer to a [previous commit](https://github.com/rkoeninger/sublime-factor/commit/d6595c4956561a660e35e68ee0ed2d93ea9b49e5) to see what to change.

All that's need to release is to add a tag, I can do that after merging your PRs.

**Comment by h0le** [comment]
Additionally, need a syntax highlighting for execute( and call( . I'll try it.

**Comment by rkoeninger** [comment]
By the way, if you add something like "Fixes #N" to your PR referencing an issue, the issue will get closed automatically.
